import type { Cluster, DailyDigest } from '@/types';

export const MOCK_CLUSTERS: Cluster[] = [
  {
    id: '1',
    topic: 'Federal Reserve Interest Rate Decision',
    topicSlug: 'federal-reserve-interest-rate',
    representativeHeadline: 'Fed Holds Rates Steady Amid Mixed Economic Signals',
    summary: 'The Federal Reserve voted 7-2 to hold interest rates at 5.25-5.5%, signaling caution as inflation remains above the 2% target. Chair Powell emphasized data-dependency while markets price in two cuts before year end.',
    articleCount: 18,
    sourceCount: 12,
    sourceBreakdown: { left: 6, center: 7, right: 4, international: 1 },
    biasAnalysis: {
      leftEmphasizes: 'Working-class burden of high borrowing costs and calls for faster rate cuts to boost employment.',
      rightEmphasizes: 'Inflation-fighting discipline and risk of premature easing reigniting price pressures.',
      consistentAcrossAll: 'The Fed held rates at 5.25-5.5% in a 7-2 vote; two more meetings remain this year.',
      whatsMissing: 'Detailed analysis of impact on commercial real estate sector and regional banks.',
    },
    heatScore: 0.42,
    substanceScore: 0.78,
    firstArticleAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 30 * 60000).toISOString(),
    articles: [
      {
        id: 'a1',
        title: 'Fed Holds Rates Steady, Signals Caution on Cuts',
        description: 'The Federal Reserve held its benchmark interest rate steady Wednesday, resisting calls to ease monetary policy as inflation remains above its 2% annual target.',
        link: '#',
        publishedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
        sourceName: 'Reuters',
        biasLabel: 'center',
        heatScore: 0.3,
        substanceScore: 0.85,
      },
      {
        id: 'a2',
        title: 'Workers Are Paying the Price for Fed\'s Rate Stubbornness',
        description: 'Millions of Americans are struggling with high mortgage rates and credit card debt while the Fed delays action. Economists say each month of delay costs households $1,200 on average.',
        link: '#',
        publishedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
        sourceName: 'The Guardian',
        biasLabel: 'left',
        heatScore: 0.65,
        substanceScore: 0.60,
      },
      {
        id: 'a3',
        title: 'Powell Right to Stand Firm: Premature Cuts Would Be Catastrophic',
        description: 'The Fed\'s restraint is the fiscally responsible choice. History shows that cutting rates before inflation is truly defeated risks a second wave that could be far worse.',
        link: '#',
        publishedAt: new Date(Date.now() - 1.5 * 3600000).toISOString(),
        sourceName: 'Wall Street Journal',
        biasLabel: 'right',
        heatScore: 0.55,
        substanceScore: 0.70,
      },
    ],
  },
  {
    id: '2',
    topic: 'AI Regulation Legislation',
    topicSlug: 'ai-regulation-legislation',
    representativeHeadline: 'Bipartisan AI Safety Bill Advances in Senate with Unexpected Speed',
    summary: 'A bipartisan group of senators advanced landmark AI safety legislation requiring mandatory testing for frontier models before deployment. Tech companies split on the bill, with smaller startups supporting oversight while major labs lobby against specific provisions.',
    articleCount: 24,
    sourceCount: 16,
    sourceBreakdown: { left: 8, center: 9, right: 5, international: 2 },
    biasAnalysis: {
      leftEmphasizes: 'Consumer protection benefits and need for accountability from powerful tech corporations.',
      rightEmphasizes: 'Regulatory overreach risks stifling innovation and ceding AI leadership to China.',
      consistentAcrossAll: 'The bill passed committee 14-8 and requires pre-deployment safety testing for models above a compute threshold.',
      whatsMissing: 'Technical details on enforcement mechanisms and how the compute threshold was determined.',
    },
    heatScore: 0.58,
    substanceScore: 0.72,
    firstArticleAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 45 * 60000).toISOString(),
    articles: [
      {
        id: 'a4',
        title: 'Senate AI Safety Bill Passes Committee in Bipartisan Vote',
        description: 'The AI Oversight and Accountability Act passed 14-8 in the Senate Commerce Committee, requiring safety evaluations for AI systems trained on more than 10^26 floating point operations.',
        link: '#',
        publishedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
        sourceName: 'Politico',
        biasLabel: 'center',
        heatScore: 0.4,
        substanceScore: 0.82,
      },
      {
        id: 'a5',
        title: 'Tech Giants\'s AI Regulation Push Is About Crushing Competition',
        description: 'OpenAI and Anthropic\'s support for AI regulation is self-serving — by lobbying for compute thresholds they can meet but startups cannot, they\'re building a moat disguised as safety.',
        link: '#',
        publishedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
        sourceName: 'Reason',
        biasLabel: 'right',
        heatScore: 0.72,
        substanceScore: 0.58,
      },
    ],
  },
  {
    id: '3',
    topic: 'Climate Agreement Implementation',
    topicSlug: 'climate-agreement-implementation',
    representativeHeadline: 'G20 Nations Miss Key Climate Funding Deadline for Second Consecutive Year',
    summary: 'Developed nations have again failed to deliver $100 billion annually in climate finance to developing countries, a commitment made in 2009. The shortfall is estimated at $17 billion, with disputes over loan vs. grant accounting at the center of the disagreement.',
    articleCount: 14,
    sourceCount: 9,
    sourceBreakdown: { left: 7, center: 4, right: 2, international: 1 },
    biasAnalysis: {
      leftEmphasizes: 'Wealthy nations\' broken promises undermine trust and disproportionately harm vulnerable populations.',
      rightEmphasizes: 'Definitional disputes over what counts as climate finance make the "$17 billion gap" figure misleading.',
      consistentAcrossAll: 'The $100 billion annual goal was missed; actual flows were approximately $83 billion by current accounting.',
      whatsMissing: 'Coverage of which specific countries are furthest from their individual commitments.',
    },
    heatScore: 0.51,
    substanceScore: 0.69,
    firstArticleAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    articles: [
      {
        id: 'a6',
        title: 'Climate Finance Pledge Falls Short Again, Developing Nations Say',
        description: 'For the second year running, G20 nations delivered approximately $83 billion in climate finance, falling $17 billion short of the landmark $100 billion annual commitment agreed in Copenhagen.',
        link: '#',
        publishedAt: new Date(Date.now() - 15 * 3600000).toISOString(),
        sourceName: 'BBC',
        biasLabel: 'center',
        heatScore: 0.45,
        substanceScore: 0.75,
      },
    ],
  },
  {
    id: '4',
    topic: 'Housing Market Affordability Crisis',
    topicSlug: 'housing-market-affordability',
    representativeHeadline: 'Home Prices Hit Record High as Inventory Stays Near Historic Lows',
    summary: 'U.S. median home prices reached $412,000 in January, a 5.1% year-over-year gain, as the number of homes for sale remained near 30-year lows. Economists debate whether the lock-in effect of low-rate mortgages or zoning restrictions are the primary culprit.',
    articleCount: 21,
    sourceCount: 14,
    sourceBreakdown: { left: 7, center: 8, right: 5, international: 1 },
    biasAnalysis: {
      leftEmphasizes: 'Corporate investor landlords and private equity accumulation of single-family homes as a structural cause.',
      rightEmphasizes: 'Local zoning laws and permitting barriers as the root cause, with deregulation as the solution.',
      consistentAcrossAll: 'Median home price is $412,000, up 5.1% YoY; inventory is at near-historic lows of 1.1 months supply.',
      whatsMissing: 'Geographic breakdown — markets like Austin and Phoenix are actually seeing price declines.',
    },
    heatScore: 0.48,
    substanceScore: 0.81,
    firstArticleAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    articles: [],
  },
  {
    id: '5',
    topic: 'Semiconductor Supply Chain',
    topicSlug: 'semiconductor-supply-chain',
    representativeHeadline: 'CHIPS Act Factories Begin Production, But Talent Gap Remains Acute',
    summary: 'The first CHIPS Act-funded semiconductor fabrication plants are coming online, marking a milestone for domestic chip production. However, manufacturers report a shortfall of 50,000 skilled technicians needed to operate facilities at scale, threatening the program\'s timelines.',
    articleCount: 11,
    sourceCount: 8,
    sourceBreakdown: { left: 3, center: 6, right: 2, international: 0 },
    biasAnalysis: {
      leftEmphasizes: 'The need for workforce development programs and union-wage requirements to ensure quality jobs.',
      rightEmphasizes: 'The CHIPS Act\'s slow bureaucratic implementation compared to private market alternatives.',
      consistentAcrossAll: 'CHIPS Act fabs are beginning production; a 50,000-technician workforce gap has been identified.',
      whatsMissing: 'Specifics on which companies received the most funding and their progress relative to commitments.',
    },
    heatScore: 0.31,
    substanceScore: 0.84,
    firstArticleAt: new Date(Date.now() - 30 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    articles: [],
  },
  {
    id: '6',
    topic: 'Social Media Mental Health Legislation',
    topicSlug: 'social-media-mental-health',
    representativeHeadline: 'States Move to Ban Under-16s from Social Media as Federal Inaction Continues',
    summary: 'Fourteen states have now passed or are advancing legislation restricting minors\' access to social media platforms, amid growing evidence linking heavy use to depression and anxiety in teenagers. Meta and TikTok are challenging the laws in court.',
    articleCount: 17,
    sourceCount: 11,
    sourceBreakdown: { left: 5, center: 7, right: 4, international: 1 },
    biasAnalysis: {
      leftEmphasizes: 'Corporate responsibility and algorithmic exploitation of children\'s developing brains for profit.',
      rightEmphasizes: 'Parental rights framework — government should empower parents, not restrict platforms directly.',
      consistentAcrossAll: '14 states have enacted or are advancing social media age restriction laws; Meta is litigating in Florida.',
      whatsMissing: 'Evidence review: studies linking social media to harm and counterarguments about causality vs. correlation.',
    },
    heatScore: 0.63,
    substanceScore: 0.67,
    firstArticleAt: new Date(Date.now() - 36 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    articles: [],
  },
  {
    id: '7',
    topic: 'Ukraine Aid Package',
    topicSlug: 'ukraine-aid-package',
    representativeHeadline: '$61 Billion Ukraine Aid Package Clears House After Months of Delay',
    summary: 'The House passed a $61 billion aid package for Ukraine in a 311-112 vote, with broad bipartisan support overcoming months of blockage. The package includes $13.8 billion in military assistance, $26 billion in defense grants, and $7.9 billion in economic support.',
    articleCount: 29,
    sourceCount: 19,
    sourceBreakdown: { left: 10, center: 12, right: 6, international: 1 },
    biasAnalysis: {
      leftEmphasizes: 'Democratic values, Western alliance solidarity, and consequences of allowing Russian aggression to succeed.',
      rightEmphasizes: 'Domestic spending priorities and questioning the strategy\'s path to resolution rather than indefinite aid.',
      consistentAcrossAll: 'House voted 311-112 for $61B in Ukraine aid; Senate passage expected before recess.',
      whatsMissing: 'Analysis of how the aid will actually change battlefield conditions given current front-line situation.',
    },
    heatScore: 0.74,
    substanceScore: 0.76,
    firstArticleAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    articles: [],
  },
  {
    id: '8',
    topic: 'Obesity Drug Market Expansion',
    topicSlug: 'obesity-drug-market',
    representativeHeadline: 'GLP-1 Drugs Show Promise Beyond Weight Loss, Cardiac Trials Reveal',
    summary: 'New clinical data suggests GLP-1 receptor agonists like semaglutide reduce cardiovascular events by 20% independent of weight loss, potentially expanding the addressable market by 40 million Americans. Insurance coverage battles are accelerating.',
    articleCount: 13,
    sourceCount: 9,
    sourceBreakdown: { left: 4, center: 7, right: 2, international: 0 },
    biasAnalysis: {
      leftEmphasizes: 'Insurance coverage gaps leaving lower-income patients unable to access life-changing treatments.',
      rightEmphasizes: 'Market-driven innovation success and concerns about Medicare spending implications.',
      consistentAcrossAll: 'SELECT trial data shows 20% reduction in major cardiovascular events with semaglutide vs. placebo.',
      whatsMissing: 'Long-term safety data beyond 5 years and real-world effectiveness vs. trial conditions.',
    },
    heatScore: 0.38,
    substanceScore: 0.88,
    firstArticleAt: new Date(Date.now() - 20 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    articles: [],
  },
  {
    id: '9',
    topic: 'College Campus Protests',
    topicSlug: 'college-campus-protests',
    representativeHeadline: 'University Presidents Face Congress Over Campus Protest Response',
    summary: 'Three Ivy League presidents testified before Congress about campus demonstrations, with lawmakers from both parties pressing them on speech policies, anti-semitism definitions, and whether protest encampments violated university rules. One president resigned hours after the hearing.',
    articleCount: 22,
    sourceCount: 15,
    sourceBreakdown: { left: 8, center: 8, right: 6, international: 0 },
    biasAnalysis: {
      leftEmphasizes: 'Free speech principles and the danger of congressional pressure on academic freedom.',
      rightEmphasizes: 'Failure to apply campus speech codes consistently and evidence of antisemitic incidents going unaddressed.',
      consistentAcrossAll: 'Three presidents testified; MIT\'s president resigned December 9th, citing the hearing as a factor.',
      whatsMissing: 'Student and faculty perspectives beyond protest organizers and administrators.',
    },
    heatScore: 0.82,
    substanceScore: 0.61,
    firstArticleAt: new Date(Date.now() - 72 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    articles: [],
  },
  {
    id: '10',
    topic: 'Space Exploration Milestones',
    topicSlug: 'space-exploration-milestones',
    representativeHeadline: 'Private Moon Landing Succeeds, First American Touchdown Since Apollo',
    summary: 'Intuitive Machines\' IM-1 lander successfully touched down near the lunar south pole, marking the first American soft landing on the Moon since Apollo 17 in 1972. The mission, part of NASA\'s Commercial Lunar Payload Services program, carried six NASA instruments.',
    articleCount: 16,
    sourceCount: 11,
    sourceBreakdown: { left: 5, center: 8, right: 2, international: 1 },
    biasAnalysis: {
      leftEmphasizes: 'Public investment in NASA\'s CLPS program enabling private sector achievements and scientific access.',
      rightEmphasizes: 'Commercial space model vindicating private sector efficiency over traditional NASA contracting.',
      consistentAcrossAll: 'IM-1 touched down near Malapert A crater; lander is operational though slightly tilted.',
      whatsMissing: 'Whether the 15-degree tilt affects mission science objectives and antenna communication.',
    },
    heatScore: 0.35,
    substanceScore: 0.79,
    firstArticleAt: new Date(Date.now() - 26 * 3600000).toISOString(),
    lastArticleAt: new Date(Date.now() - 7 * 3600000).toISOString(),
    articles: [],
  },
];

export const MOCK_DIGEST: DailyDigest = {
  id: 'digest-1',
  digestDate: new Date().toISOString(),
  summary: `Good morning. Here's your world in 60 seconds.

The Federal Reserve held rates steady in a 7-2 vote, citing sticky inflation above the 2% target. Markets now price in just two cuts this year, down from six at the start of 2024.

In Washington, a bipartisan AI safety bill cleared Senate committee 14-8, requiring safety testing for frontier models before public deployment. Tech giants are split: OpenAI supports it, while some smaller labs warn of competitive harm.

On housing, median home prices hit a record $412,000 as inventory stays near 30-year lows. Economists are divided on whether the mortgage lock-in effect or local zoning is the bigger culprit.

The House passed $61 billion in Ukraine aid 311-112 after months of blockage. Senate passage is expected before recess.

And in a rare moment of wonder, a private American spacecraft touched down on the Moon for the first time since Apollo 17 — 1972. The lander is operational, though slightly tilted.

Ten stories. One world. You're caught up.`,
  keyTopics: ['Federal Reserve', 'AI Regulation', 'Housing Crisis', 'Ukraine Aid', 'Moon Landing'],
  closingLine: "You're caught up.",
  clusterCount: 10,
  articleCount: 185,
};
